// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: DarkUI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Lampe = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Lampe, &ui_img_lampe_png);
    lv_obj_set_width(ui_Lampe, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Lampe, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Lampe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lampe, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Lampe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Text = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Text, &ui_img_text_v2_png);
    lv_obj_set_width(ui_Text, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Text, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Text, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Text, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Text, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
