version: 3

# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

############################################################
#  Overrides
############################################################

overrides:
    - if: "'hotfix' in labels"
      status: success
      explanation: "Hotfix label added, bypassing reviews"

    ############################################################
    #  Draft PRs
    ############################################################
    - if: "draft"
      status: pending
      explanation: "PR is draft, pending review"

    ############################################################
    #  License Checks
    ############################################################
    - if: "'*license/cla*' not in statuses.successful"
      status: pending
      explanation: "CLA must be agreed to by all contributors"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - if: "base.ref != 'main'"
      status: success
      explanation: "Review not required unless merging to main"

    ############################################################
    #  Required status checks
    ############################################################
    # - if: "'*restyle*' not in statuses.successful"
    #   status: failure
    #   explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Require Issues
    ############################################################
    # disabling until we have PRs up to date
    #     - if: "'*issue*' not in statuses.successful"
    #       status: failure
    #       explanation: "An issue is required for all PRs"

    ############################################################
    #  Fast tracking
    ############################################################
    - if: "'fast track' in labels"
      status: success
      explanation: "PR has been fast tracked, bypassing reviews"

    ############################################################
    #  Automatic PRs for Releases
    ############################################################
    - if: "'automated pr' in labels"
      status: success
      explanation: "Automatic PR for Releases, bypassing reviews"

############################################################
#  Notifications
############################################################

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Required Reviewers
    ############################################################
    required-review:
        type: required
        reviews:
            required: 1
            request: 10
        reviewers:
            users:
              - lauckhart
              - Apollon77
              - vves
            teams:
              - matter-js-reviewers
        labels:
            approved: "review - approved"
            pending: "review - pending"
            rejected: "review - changed requested"

